# Generated by Django 4.1.1 on 2022-09-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagent',
            old_name='user_id',
            new_name='user',
        ),
    ]
