# Generated by Django 4.1.1 on 2022-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_user_id_deliveryagent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryagent',
            old_name='user',
            new_name='user_id',
        ),
    ]
