# Generated by Django 4.1.1 on 2022-09-18 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Delivery Boy', 'Delivery Boy'), ('Customer', 'Customer')], max_length=50),
        ),
    ]
