# Generated by Django 3.1.3 on 2021-01-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Subscription',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
