# Generated by Django 3.1.3 on 2021-01-29 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='Subscription',
        ),
    ]
