# Generated by Django 3.1.5 on 2021-01-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_shop_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('selling_price', models.IntegerField(blank=True, null=True)),
                ('km_driven', models.IntegerField(blank=True, null=True)),
                ('fuel', models.CharField(blank=True, max_length=255, null=True)),
                ('seller_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
