# Generated by Django 3.1.5 on 2021-01-30 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_testcar_selling_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCar',
        ),
    ]
