# Generated by Django 3.1.5 on 2021-01-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_testcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('fuel', models.CharField(max_length=255)),
                ('seller_type', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
    ]
