# Generated by Django 3.1.5 on 2021-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_testcar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dboy_id',
            field=models.IntegerField(null=True),
        ),
    ]
