# Generated by Django 3.1.5 on 2021-01-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_dboy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dboy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
