# Generated by Django 4.1.1 on 2022-09-18 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='email_id',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone_no',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
