# Generated by Django 4.1.1 on 2022-09-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pin_no',
            field=models.IntegerField(),
        ),
    ]
