# Generated by Django 4.1.1 on 2022-09-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='body',
            new_name='author_desc',
        ),
    ]
