# Generated by Django 4.1.1 on 2022-09-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_categories_remove_product_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
