# Generated by Django 4.1.1 on 2022-09-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_categories_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
