# Generated by Django 4.1.1 on 2022-09-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
    ]
