# Generated by Django 6.0.2 on 2026-02-06 17:59

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_categories_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
